[project]
name = "rename_ha_registry_entities"
version = "0.1.0"
description = "Rename Home Assistant entities"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "requests>=2.32.5",
    "websockets>=16.0",
]
